export const ICON_URLS = {
  heart: '/assets/icons/heart.svg',
  arrow: '/assets/icons/arrow.svg',
  arrowLeft: '/assets/icons/arrow-left.svg',
  arrowRight: '/assets/icons/arrow-right.svg',
  arrowDown: '/assets/icons/arrow-down.svg',
  calendar: '/assets/icons/calendar.svg',
  marker: '/assets/icons/marker.svg',
  route: '/assets/icons/route.svg',
  bookmarkActive: '/assets/icons/bookmark-active.svg',
  bookmarkInactive: '/assets/icons/bookmark-inactive.svg',
  heartActive: '/assets/icons/heart-active.svg',
  heartInactive: '/assets/icons/heart-inactive.svg',
  share: '/assets/icons/share.svg',
  search: '/assets/icons/search.svg',
  searchBlue: '/assets/icons/search-blue.svg',
  close: '/assets/icons/close.svg',
  thinClose: '/assets/icons/close-thin.svg',
  plus: '/assets/icons/plus.svg',
  pencil: '/assets/icons/pencil.svg',
  comment: '/assets/icons/comment.svg',
  commentRound: '/assets/icons/comment-round.svg',
  bookmarkThumb: '/assets/icons/bookmark-thumb.svg',
  bookmarkThumbActive: '/assets/icons/bookmark-thumb-active.svg',
  recommendActive: '/assets/icons/recommend-active.svg',
  recommendInactive: '/assets/icons/recommend-inactive.svg',
  thinArrow: '/assets/icons/thinArrow.svg',
  thinArrowActive: '/assets/icons/thinArrow-active.svg',
  thinArrowDisabled: '/assets/icons/thinArrow-disabled.svg',
  alert: '/assets/icons/alert.svg'
};

export type IconName = keyof typeof ICON_URLS;
